# Generated by Django 5.2.16 on 2026-10-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDelegationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('credential_version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentinput',
            name='acting_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_inputs', to='app_core.businessapplication'),
        ),
        migrations.AddField(
            model_name='agentinput',
            name='app_delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_inputs', to='app_core.userappdelegation'),
        ),
        migrations.AddField(
            model_name='agentinput',
            name='credential_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userappdelegation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_delegations', to='app_core.agent'),
        ),
        migrations.AddField(
            model_name='userappdelegation',
            name='credential_version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='userappdelegation',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_delegations', to='app_core.agentdefinition'),
        ),
        migrations.AlterField(
            model_name='userappdelegation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agentinput',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acting_app__isnull', True), ('app_delegation__isnull', True), ('credential_version__isnull', True)), models.Q(('acting_app__isnull', False), ('app_delegation__isnull', False), ('credential_version__gt', 0), ('credential_version__isnull', False)), _connector='OR'), name='agent_input_app_origin_complete'),
        ),
        migrations.AddConstraint(
            model_name='userappdelegation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('definition__isnull', False)), models.Q(('agent__isnull', False), ('definition__isnull', True)), _connector='OR'), name='app_delegation_target_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='userappdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('credential_version__gt', 0)), name='app_delegation_version_positive'),
        ),
        migrations.AddField(
            model_name='appdelegationauditevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appdelegationauditevent',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='app_core.userappdelegation'),
        ),
        migrations.AddConstraint(
            model_name='appdelegationauditevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('issued', 'rotated', 'revoked'))), name='app_delegation_audit_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='appdelegationauditevent',
            constraint=models.CheckConstraint(condition=models.Q(('credential_version__gt', 0)), name='app_delegation_audit_version_positive'),
        ),
    ]
