# Generated by Django 5.2.16 on 2026-10-05 03:00

from django.db import migrations, models


def transfer_browser_credentials(apps, schema_editor):
    legacy = apps.get_model('sessions', 'Session')
    current = apps.get_model('app_core', 'BrowserLoginSession')
    alias = schema_editor.connection.alias
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('LOCK TABLE django_session IN ACCESS EXCLUSIVE MODE')
    batch = []
    for row in legacy.objects.using(alias).values('session_key', 'session_data', 'expire_date').iterator(chunk_size=500):
        batch.append(current(**row))
        if len(batch) == 500:
            current.objects.using(alias).bulk_create(batch)
            batch = []
    if batch:
        current.objects.using(alias).bulk_create(batch)
    # A logout must not leave a second copy which could authenticate on rollback.
    # Keys, signed data and original finite deadlines are preserved in the new table.
    legacy.objects.using(alias).all().delete()


def refuse_credential_loss_on_reverse(apps, schema_editor):
    if apps.get_model('app_core', 'BrowserLoginSession').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Cannot downgrade while browser credentials exist; revoke them explicitly before downgrade')


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_persistent_app_delegations'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserLoginSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expire date')),
            ],
            options={
                'verbose_name': 'browser login',
                'verbose_name_plural': 'browser logins',
            },
        ),
        migrations.RunPython(transfer_browser_credentials, refuse_credential_loss_on_reverse),
    ]
