# Generated by Django 5.2.16 on 2026-10-05 03:23

import app_core.models
import django.db.models.deletion
from django.db import migrations, models


def refuse_reverse_with_business_branches(apps, schema_editor):
    branch = apps.get_model('app_core', 'BusinessAgentBranch')
    if branch.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Cannot downgrade while persistent business agent branches exist')


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_persistent_browser_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAgentBranch',
            fields=[
                ('id', models.CharField(default=app_core.models.new_business_agent_branch_id, max_length=64, primary_key=True, serialize=False)),
                ('business_user_id', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_branch', to='app_core.agent')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_branches', to='app_core.businessapplication')),
                ('root_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_branches', to='app_core.agent')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_branch', to='app_core.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('app', 'root_agent', 'business_user_id'), name='business_branch_subject_unique'), models.CheckConstraint(condition=models.Q(('business_user_id', ''), _negated=True), name='business_branch_subject_nonempty'), models.CheckConstraint(condition=models.Q(('root_agent', models.F('agent')), _negated=True), name='business_branch_agent_distinct')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_reverse_with_business_branches),
    ]
