use crate::errors::RuntimeHostError;
use crate::host_protocol;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RuntimeHostCommand {
    Initialize,
    AppExit,
    SessionList,
    SessionDiagnostics,
    SessionGet,
    SessionCreate,
    SessionActivate,
    SessionDelete,
    SessionProjectionGet,
    SessionUpdate,
    SessionReorder,
    AgentRuntimeConfigGet,
    AgentRuntimeConfigReset,
    AgentRuntimeConfigSet,
    AgentRuntimeModelTest,
    McpCatalog,
    McpConfigure,
    PluginList,
    PluginDetail,
    PluginInstall,
    PluginRemove,
    PluginSetEnabled,
    PluginReload,
    PluginSourceRef,
    PluginCatalogState,
    SkillSourceList,
    SkillSourceAdd,
    SkillSourceRemove,
    SkillSourceSetEnabled,
    SkillSourceRef,
    SkillCatalog,
    SkillDetail,
    SkillSetEnabled,
    SkillReload,
    AgentStateGet,
    AgentContextUsageGet,
    AgentContextCompact,
    AgentRuntimeGarbageCollect,
    TranscriptProjection,
    AgentInput,
    AgentSupplement,
    AgentAnswerNow,
    AgentQuestionAnswer,
    AgentRunList,
    AgentRunStreamReplay,
    AgentRunAttach,
    AgentRunDetach,
    AgentRunDetachViewer,
    AgentRunCancel,
    AgentRuntimeJobList,
    AgentRuntimeJobGet,
    AgentDeadLetterList,
    AgentDeadLetterGet,
    AgentDeadLetterDismiss,
    AgentDeadLetterReplay,
    ProcessCapture,
    SidecarStart,
    SidecarStop,
    SidecarList,
    WorkspaceGet,
    WorkspaceActivate,
    WorkspaceOpenFolder,
    WorkspaceRevealFolder,
    WorkspaceRename,
    WorkspaceRemove,
    WorkspaceReset,
    WorkspaceFileTree,
    WorkspaceReadFile,
    WorkspaceGitStatusGet,
    WorkspaceGitDiffGet,
    WorkspaceGitFileDiffGet,
    WorkspaceGitHubCliStatusGet,
    DesktopFilePreviewRead,
}

impl RuntimeHostCommand {
    pub(crate) fn parse(raw: &str) -> Result<Self, RuntimeHostError> {
        match raw.trim() {
            "initialize" => Ok(Self::Initialize),
            "app_exit" => Ok(Self::AppExit),
            "session/list" => Ok(Self::SessionList),
            "_centaeris/session/diagnostics" => Ok(Self::SessionDiagnostics),
            "session/load" => Ok(Self::SessionGet),
            "session/new" => Ok(Self::SessionCreate),
            "_centaeris/session/activate" => Ok(Self::SessionActivate),
            "_centaeris/session/delete" => Ok(Self::SessionDelete),
            "_centaeris/session/project" => Ok(Self::SessionProjectionGet),
            "_centaeris/session/update_metadata" => Ok(Self::SessionUpdate),
            "_centaeris/session/reorder" => Ok(Self::SessionReorder),
            "agent_runtime_config_get" => Ok(Self::AgentRuntimeConfigGet),
            "agent_runtime_config_reset" => Ok(Self::AgentRuntimeConfigReset),
            "agent_runtime_config_set" => Ok(Self::AgentRuntimeConfigSet),
            "agent_runtime_model_test" => Ok(Self::AgentRuntimeModelTest),
            "mcp/catalog" => Ok(Self::McpCatalog),
            "mcp/configure" => Ok(Self::McpConfigure),
            "plugin/list" => Ok(Self::PluginList),
            "plugin/detail" => Ok(Self::PluginDetail),
            "plugin/install" => Ok(Self::PluginInstall),
            "plugin/remove" => Ok(Self::PluginRemove),
            "plugin/set_enabled" => Ok(Self::PluginSetEnabled),
            "plugin/reload" => Ok(Self::PluginReload),
            "plugin/source_ref" => Ok(Self::PluginSourceRef),
            "plugin/catalog_state" => Ok(Self::PluginCatalogState),
            "skill/source/list" => Ok(Self::SkillSourceList),
            "skill/source/add" => Ok(Self::SkillSourceAdd),
            "skill/source/remove" => Ok(Self::SkillSourceRemove),
            "skill/source/set_enabled" => Ok(Self::SkillSourceSetEnabled),
            "skill/source/ref" => Ok(Self::SkillSourceRef),
            "skill/catalog" => Ok(Self::SkillCatalog),
            "skill/detail" => Ok(Self::SkillDetail),
            "skill/set_enabled" => Ok(Self::SkillSetEnabled),
            "skill/reload" => Ok(Self::SkillReload),
            "agent_state_get" => Ok(Self::AgentStateGet),
            "agent_context_usage_get" => Ok(Self::AgentContextUsageGet),
            "_centaeris/session/compact_context" => Ok(Self::AgentContextCompact),
            "agent_runtime_garbage_collect" => Ok(Self::AgentRuntimeGarbageCollect),
            "transcript/project" => Ok(Self::TranscriptProjection),
            "session/prompt" => Ok(Self::AgentInput),
            "_centaeris/session/supplement" => Ok(Self::AgentSupplement),
            "_centaeris/session/answer_now" => Ok(Self::AgentAnswerNow),
            "_centaeris/session/answer_question" => Ok(Self::AgentQuestionAnswer),
            "_centaeris/session/agent-runs" => Ok(Self::AgentRunList),
            "_centaeris/session/agent-runs/replay" => Ok(Self::AgentRunStreamReplay),
            "_centaeris/session/agent-runs/attach" => Ok(Self::AgentRunAttach),
            "_centaeris/session/agent-runs/detach" => Ok(Self::AgentRunDetach),
            "_centaeris/session/agent-runs/detach-viewer" => Ok(Self::AgentRunDetachViewer),
            "_centaeris/session/agent-runs/cancel" => Ok(Self::AgentRunCancel),
            "agent_runtime_job_list" => Ok(Self::AgentRuntimeJobList),
            "agent_runtime_job_get" => Ok(Self::AgentRuntimeJobGet),
            "agent_dead_letter_list" => Ok(Self::AgentDeadLetterList),
            "agent_dead_letter_get" => Ok(Self::AgentDeadLetterGet),
            "agent_dead_letter_dismiss" => Ok(Self::AgentDeadLetterDismiss),
            "agent_dead_letter_replay" => Ok(Self::AgentDeadLetterReplay),
            "process_capture" => Ok(Self::ProcessCapture),
            "sidecar_start" => Ok(Self::SidecarStart),
            "sidecar_stop" => Ok(Self::SidecarStop),
            "sidecar_list" => Ok(Self::SidecarList),
            "workspace_get" => Ok(Self::WorkspaceGet),
            "workspace_activate" => Ok(Self::WorkspaceActivate),
            "workspace_open_folder" => Ok(Self::WorkspaceOpenFolder),
            "workspace_reveal_folder" => Ok(Self::WorkspaceRevealFolder),
            "workspace_rename" => Ok(Self::WorkspaceRename),
            "workspace_remove" => Ok(Self::WorkspaceRemove),
            "workspace_reset" => Ok(Self::WorkspaceReset),
            "workspace_file_tree" => Ok(Self::WorkspaceFileTree),
            "workspace_read_file" => Ok(Self::WorkspaceReadFile),
            "workspace_git_status_get" => Ok(Self::WorkspaceGitStatusGet),
            "workspace_git_diff_get" => Ok(Self::WorkspaceGitDiffGet),
            "workspace_git_file_diff_get" => Ok(Self::WorkspaceGitFileDiffGet),
            "workspace_git_github_cli_status_get" => Ok(Self::WorkspaceGitHubCliStatusGet),
            "desktop_file_preview_read" => Ok(Self::DesktopFilePreviewRead),
            "" => Err(RuntimeHostError::invalid_request("command is required")),
            value if host_protocol::is_registered_host_command(value) => Err(
                RuntimeHostError::new("sidecar_command_not_implemented", value),
            ),
            value => Err(RuntimeHostError::unknown_command(value)),
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::host_protocol;

    const LOCAL_RUNTIME_COMMANDS: &[&str] = &[
        "initialize",
        "app_exit",
        "session/list",
        "_centaeris/session/diagnostics",
        "session/load",
        "session/new",
        "_centaeris/session/activate",
        "_centaeris/session/delete",
        "_centaeris/session/project",
        "_centaeris/session/update_metadata",
        "_centaeris/session/reorder",
        "agent_runtime_config_get",
        "agent_runtime_config_reset",
        "agent_runtime_config_set",
        "agent_runtime_model_test",
        "mcp/catalog",
        "mcp/configure",
        "plugin/list",
        "plugin/detail",
        "plugin/install",
        "plugin/remove",
        "plugin/set_enabled",
        "plugin/reload",
        "plugin/source_ref",
        "plugin/catalog_state",
        "skill/source/list",
        "skill/source/add",
        "skill/source/remove",
        "skill/source/set_enabled",
        "skill/source/ref",
        "skill/catalog",
        "skill/detail",
        "skill/set_enabled",
        "skill/reload",
        "agent_state_get",
        "agent_context_usage_get",
        "_centaeris/session/compact_context",
        "agent_runtime_garbage_collect",
        "transcript/project",
        "session/prompt",
        "_centaeris/session/supplement",
        "_centaeris/session/answer_now",
        "_centaeris/session/answer_question",
        "_centaeris/session/agent-runs",
        "_centaeris/session/agent-runs/replay",
        "_centaeris/session/agent-runs/attach",
        "_centaeris/session/agent-runs/detach",
        "_centaeris/session/agent-runs/detach-viewer",
        "_centaeris/session/agent-runs/cancel",
        "agent_runtime_job_list",
        "agent_runtime_job_get",
        "agent_dead_letter_list",
        "agent_dead_letter_get",
        "agent_dead_letter_dismiss",
        "agent_dead_letter_replay",
        "process_capture",
        "sidecar_start",
        "sidecar_stop",
        "sidecar_list",
        "workspace_get",
        "workspace_activate",
        "workspace_open_folder",
        "workspace_reveal_folder",
        "workspace_rename",
        "workspace_remove",
        "workspace_reset",
        "workspace_file_tree",
        "workspace_read_file",
        "workspace_git_status_get",
        "workspace_git_diff_get",
        "workspace_git_file_diff_get",
        "workspace_git_github_cli_status_get",
        "desktop_file_preview_read",
    ];

    #[test]
    fn known_runtime_host_commands_are_registered_in_host_protocol() {
        for command in LOCAL_RUNTIME_COMMANDS {
            assert!(
                host_protocol::is_registered_host_command(command),
                "missing core host protocol registration for {command}"
            );
        }
    }
}
