import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, realpath, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { runBrowser, waitFor } from "./browserHarness.mjs";

for (const scenario of [{ width: 1280, language: "en", locale: "en-US" }, { width: 390, language: "zh-CN", locale: "zh-CN", reduced: true }]) for (const theme of ["light", "dark"]) test(`transcript message copy/time (${theme}, ${scenario.width}px, ${scenario.language})`, async () => {
  const profile = await mkdtemp(join(tmpdir(), "centaeris-transcript-actions-"));
  const server = await createServer({ root: fileURLToPath(new URL("../..", import.meta.url)), server: { port: 0, host: "127.0.0.1", strictPort: false } });
  try {
    await server.listen();
    const url = `${server.resolvedUrls.local[0]}tests/browser/transcript-message-actions.html?${new URLSearchParams({ language: scenario.language, theme })}`;
    await runBrowser(url, { ...scenario, timeZone: "Asia/Taipei" }, profile, async ({ evaluate, send, press, frame }) => {
      await waitFor(() => evaluate("window.messageActionsFixture?.ready"), "message actions fixture");
      const state = id => evaluate(`(() => { const row = messageActionsFixture.row(${JSON.stringify(id)}); const meta = row.querySelector('.transcriptMessageMeta'); const button = meta?.querySelector('button'); return { buttons: row.querySelectorAll('.transcriptMessageMeta button').length, time: meta?.querySelector('time')?.getAttribute('datetime') ?? null, opacity: meta ? getComputedStyle(meta).opacity : null, label: button?.getAttribute('aria-label') }; })()`);
      const click = id => evaluate(`messageActionsFixture.row(${JSON.stringify(id)}).querySelector('.transcriptMessageMeta button').click()`);
      for (const id of ["user", "answer", "stage", "no-time"]) assert.equal((await state(id)).buttons, 1, `${id} offers copy`);
      assert.equal((await state("answer")).label, scenario.language === "en" ? "Copy answer" : "复制回答");
      assert.equal((await state("stage")).label, scenario.language === "en" ? "Copy" : "复制");
      assert.equal((await state("user")).time, "2026-10-04T06:35:00.000Z", "user time uses authoritative event time");
      assert.equal((await state("answer")).time, "2026-10-04T06:35:00.000Z", "answer time uses authoritative event time");
      assert.equal((await state("stage")).time, "2026-10-04T06:35:00.000Z", "immutable stage summary retains authoritative event time");
      assert.equal((await state("no-time")).time, null, "history without source time has no fabricated time");
      assert.equal((await state("running")).buttons, 0, "streaming text has no sealed actions/time");
      assert.equal((await state("reasoning")).buttons, 0, "reasoning has no public-message copy");
      const hover = await evaluate("(() => { const r = messageActionsFixture.row('answer').getBoundingClientRect(); return { x: r.left + 10, y: r.top + 10 }; })()");
      if (scenario.width === 1280) assert.equal((await state("answer")).opacity, "0", "desktop actions begin hidden");
      await send("Input.dispatchMouseEvent", { type: "mouseMoved", ...hover });
      await waitFor(async () => (await state("answer")).opacity === "1", "hover reveals actions");
      await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: 1, y: 1 });
      await evaluate("document.body.tabIndex = -1; document.body.focus()");
      await press("Tab");
      assert.equal(await evaluate("document.activeElement === messageActionsFixture.row('user').querySelector('button')"), true, "Tab reaches message copy");
      await waitFor(async () => (await state("user")).opacity === "1", "keyboard focus reveals actions");
      assert.equal(await evaluate("getComputedStyle(document.activeElement).outlineStyle !== 'none'"), true, "copy keyboard focus remains visible");
      await press("Enter");
      await waitFor(() => evaluate("messageActionsFixture.copied.length === 1"), "keyboard copy");
      assert.equal(await evaluate("messageActionsFixture.copied[0]"), "你好");
      assert.equal(await evaluate("messageActionsFixture.row('user').querySelector('[role=status]').textContent"), scenario.language === "en" ? "Copied." : "已复制。", "copy success is localized");
      await click("answer"); await click("stage");
      await waitFor(() => evaluate("messageActionsFixture.copied.length === 3"), "answer/stage copy");
      assert.deepEqual(await evaluate("messageActionsFixture.copied.slice(1)"), ["**回答**\n完整原文", "阶段总结 **原文**"], "copy preserves original markdown");
      await evaluate("messageActionsFixture.clipboardFailure(true)"); await click("answer");
      await waitFor(() => evaluate("!!messageActionsFixture.row('answer').querySelector('[role=alert]')"), "clipboard error feedback");
      assert.equal(await evaluate("messageActionsFixture.row('answer').querySelector('[role=alert]').textContent"), scenario.language === "en" ? "Unable to copy. Select and copy the message manually." : "无法复制。请选中消息并手动复制。", "clipboard failure is localized");
      assert.equal(await evaluate("messageActionsFixture.copied.length"), 3, "clipboard refusal does not claim success");
      await evaluate("messageActionsFixture.clipboardFailure(false); messageActionsFixture.completeRunning()");
      assert.equal((await state("running")).buttons, 1, "completion restores actions"); await click("running");
      await waitFor(() => evaluate("messageActionsFixture.copied.length === 4"), "completed stream copy");
      assert.equal(await evaluate("messageActionsFixture.copied[3]"), "流式完成 **完整回答**");
      await evaluate("messageActionsFixture.loadHistory()"); await click("history");
      await waitFor(() => evaluate("messageActionsFixture.copied.length === 5"), "paged history copy");
      assert.equal((await state("history")).time, "2026-10-03T06:35:00.000Z");
      assert.equal(await evaluate("messageActionsFixture.copied[4]"), "较早 **历史原文**");
      await evaluate("messageActionsFixture.reference()");
      await waitFor(() => evaluate("messageActionsFixture.requests.length >= 1"), "reference display read");
      const beforeDisplayContinuation = await evaluate("messageActionsFixture.requests.length");
      await evaluate("messageActionsFixture.resolve(messageActionsFixture.requests.length - 1)");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeDisplayContinuation}`), "display continuation");
      const displayPending = await evaluate("messageActionsFixture.requests.length - 1");
      await click("long");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${displayPending + 1}`), "copy loads complete source independently");
      const beforeDuplicate = await evaluate("messageActionsFixture.requests.length");
      await click("long"); await frame();
      assert.equal(await evaluate("messageActionsFixture.requests.length"), beforeDuplicate, "repeated click cannot duplicate a pending copy");
      assert.equal(await evaluate("messageActionsFixture.copied.length"), 5, "partial source is never copied");
      const beforeFinal = await evaluate("messageActionsFixture.requests.length");
      await evaluate("messageActionsFixture.resolve(messageActionsFixture.requests.length - 1)");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeFinal}`), "copy final content range");
      await evaluate("messageActionsFixture.resolve(messageActionsFixture.requests.length - 1)");
      await waitFor(() => evaluate("messageActionsFixture.copied.length === 6"), "long original copy");
      assert.equal(await evaluate("messageActionsFixture.copied[5] === messageActionsFixture.rawReference"), true, "copy includes all raw Chinese text rather than displayed prefix");
      assert.equal(await evaluate("messageActionsFixture.row('long').querySelector('.workspaceTerminalAnswer').textContent.includes('原文末尾')"), false, "copy succeeds while display still holds its prefix");
      await evaluate(`messageActionsFixture.resolve(${displayPending})`);
      const beforeFailedView = await evaluate("messageActionsFixture.requests.length");
      await evaluate("messageActionsFixture.reference()");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeFailedView}`), "new reference display read");
      const beforeFailedContinuation = await evaluate("messageActionsFixture.requests.length");
      await evaluate("messageActionsFixture.resolve(messageActionsFixture.requests.length - 1)");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeFailedContinuation}`), "failed reference display continuation");
      const beforeFailedCopy = await evaluate("messageActionsFixture.requests.length");
      await click("long");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeFailedCopy}`), "failed source copy");
      await evaluate("messageActionsFixture.resolve(messageActionsFixture.requests.length - 1, true)");
      await waitFor(() => evaluate("!!messageActionsFixture.row('long').querySelector('.transcriptMessageMeta [role=alert]')"), "failed full-source copy feedback");
      assert.equal(await evaluate("messageActionsFixture.copied.length"), 6, "failed source never copies the available prefix");
      const beforeCancelledCopy = await evaluate("messageActionsFixture.requests.length");
      await click("long");
      await waitFor(() => evaluate(`messageActionsFixture.requests.length > ${beforeCancelledCopy}`), "source copy retry");
      const cancelledRequest = await evaluate("messageActionsFixture.requests.length - 1");
      await evaluate("messageActionsFixture.replace()");
      assert.equal(await evaluate(`messageActionsFixture.requests[${cancelledRequest}].signal.aborted`), true, "changing view cancels the source copy");
      await evaluate(`messageActionsFixture.resolve(${cancelledRequest})`); await frame();
      assert.equal(await evaluate("messageActionsFixture.copied.length"), 6, "late old-view content cannot reach clipboard");
      assert.equal(await evaluate("document.getElementById('host').textContent"), "", "changing view releases copied state and content");
    });
  } finally {
    await server.close();
    const resolved = await realpath(profile);
    assert.equal(dirname(resolved).toLowerCase(), (await realpath(tmpdir())).toLowerCase());
    assert.ok(basename(resolved).startsWith("centaeris-transcript-actions-"));
    await rm(resolved, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
  }
});
